parameters: {}

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'

    # -----------------------------------------
    # Neo4j Laudis
    # -----------------------------------------
    Laudis\Neo4j\Contracts\ClientInterface:
        factory: ['Laudis\Neo4j\ClientBuilder', 'create']
        calls:
            - method: withDriver
              arguments:
                  - 'default'
                  - '%env(NEO4J_URL)%'
            - method: build
